! Thermally Driven Convection Generated by Reaction Fronts in Viscous Fluids
! https://doi.org/10.3390/sym16030269

program main_explicit11_12
  use iso_fortran_env, only: dp=>real64   
  use tridiag_mod
  implicit none
  !---------------- parametros ------------------------------------------
  integer,parameter :: nx=2000, nt=5000000, nt_stabilizer=5000000, nq = 150
  real(dp),parameter :: dx=0.5_dp, dt=4.0e-4_dp
  real(dp),parameter :: Le=20._dp, Sc=400._dp, Ra= 0.3_dp, q_max=0.3_dp
  real(dp),parameter :: v0=1._dp/sqrt(2._dp)-0.0023_dp
  integer, parameter :: noise_ini = 960, noise_end=1040
  real(dp) :: step_size_q
  real(dp), dimension(nq) :: q

  !---- Fields ----------------------------------------------------------
  !---- No dynamic arrays, hardcoding lenghts
  real(dp) :: C_old(nx),C_new(nx),T_old(nx),T_new(nx), C_init(nx), T_init(nx)
  real(dp) :: Cq_old(nx),Cq_new(nx),Tq_old(nx),Tq_new(nx)
  real(dp) :: Wq_old(nx),Wq_new(nx),Psiq_old(nx),Psiq_new(nx)

  real(dp), dimension(nq, nx) :: C0_save, T0_save, Cq_save, Tq_save, Wq_save, Psiq_save

  !----- coefficients ---------------------------------------
  real(dp):: a_vort(nx), b_vort(nx), c_vort(nx), d_vort(nx)    ! Vorticity
  real(dp):: a_str(nx),  b_str(nx),  c_str(nx),  d_str(nx)     ! Stream Function
  ! Arrays of size nx
  ! Arrays a and c are logically padded: a(1) = 0 and c(nx-2) = 0

  !----- grwoth rate ---------------------------------------
  real(dp) :: growth_rate(nq) 
  real(dp):: Cq_max_old = 0, Cq_max_new = 0
  real(dp):: growth_rate_new = 0, growth_rate_old = 0, growth_rate_relative = 0
  logical :: flag_growth_rate = .true.
  logical :: flag_log_form = .true.
  !!---------------- auxiliares ------------------------------------------
  integer :: i,j,k,save_cnt,prog_step, jj, growth_steps = 10000
  real(dp) :: t0,tcur,pct
  integer  :: nseed,nxm,left,right
  integer, allocatable :: seed(:)
  real(dp) :: r
  logical :: debug= .true.
  logical :: nan_here 
  logical, parameter :: normalized_sc = .true.  ! <- FLAG: true usa normalización Sc*dt

  ! --- Sufijo con Le, Ra (±xx.x) y Sc; sustituye "." -> "p"
character(len=32) :: suffix, raw

! 1) Formato:  SP = “Sign Plus”  |  F0.1 = un decimal (ajusta a F0.2, F0.3, … si lo necesitas)
write(raw,'("Le",I0,"Ra",SP,F0.1,"Sc",I0)') int(Le), Ra, int(Sc)
suffix = adjustl(trim(raw))     ! recorta espacios a la izquierda/derecha

! 2) Sustituir el punto decimal por 'p'
do i = 1, len_trim(suffix)
   if (suffix(i:i) == '.') suffix(i:i) = 'p'
end do



  !! Check what is declared as parameters
  write(*, *) "Reaction difussion" 
  write(*,*) "model thermally driven convection"

  write(*, *) "Mesh parameters"
  write(*,*) "Number of points"
  write(*, "(2(A8,I10, 3X))") "Space: ",nx,"Time: ", nt
  write(*,*) "Space between points"
  write(*, "(2(A8,F15.7, 3X))") "Space: ",dx,"Time: ", dt

  !======================================================================
  ! Saving Files
  !======================================================================
  open(10, file = 'C0_'//suffix//'.txt',   status = 'replace')
  open(11, file = 'T0_'//suffix//'.txt',   status = 'replace')
  open(12, file = 'Cq_'//suffix//'.txt',   status = 'replace')
  open(13, file = 'Tq_'//suffix//'.txt',   status = 'replace')
  open(14, file = 'Wq_'//suffix//'.txt',   status = 'replace')
  open(15, file = 'Psiq_'//suffix//'.txt', status = 'replace')
  open(16, file = 'growth_rate_'//suffix//'.txt', status = 'replace')

  
  !======================================================================
  ! Time loop for C0 and T0 (in order to have stable flat front)
  !======================================================================
  ! Note: we need to check that the flat front for C0 and T0 start at the middle position of noise Cq, Tq
  write(*,*) "=== Starting stabilization loop for C0 and T0 ==="
  C_old=0._dp 
  T_old=0._dp
  C_old(1:noise_ini)=1._dp
  T_old(1:noise_ini)=1._dp
  do i=noise_ini+1, noise_end
      call random_number(r); C_old(i) = 1.0e-3_dp * r
      call random_number(r); T_old(i) = 1.0e-3_dp * r
      call random_number(r); Cq_old(i) = 1.0e-3_dp * r
      call random_number(r); Tq_old(i) = 1.0e-3_dp * r
  enddo
  ! C0 = [1,1... random...0,0]
  ! T0 = [1,1... random...0,0]

  do i=0,nt_stabilizer
    !======================================================================
    ! Solving for flat front solutions C0 and T0 using Euler explicit methods
    ! C0
    C_new(2:nx-1) = C_old(2:nx-1)+ &
                    dt/dx**2*(C_old(3:nx)-2*C_old(2:nx-1)+C_old(1:nx-2))+ &
                    dt*(C_old(2:nx-1)**2)*(1-C_old(2:nx-1))+&
                    v0*dt/(2*dx)*(C_old(3:nx)-C_old(1:nx-2))
    ! T0
    T_new(2:nx-1)=T_old(2:nx-1)+&
                    Le*dt/dx**2*(T_old(3:nx)-2*T_old(2:nx-1)+T_old(1:nx-2))+ &
                    dt*(C_old(2:nx-1)**2)*(1-C_old(2:nx-1))+&
                    v0*dt/(2*dx)*(T_old(3:nx)-T_old(1:nx-2))
    ! Update
    C_old = C_new
    T_old = T_new  
    ! C0 and T0 Boundary conditions 
    ! C0(1)=1 = 1, C0(nx)=0 (DIRICHLET)
    C_old(1) = 1; C_old(nx) = 0

    ! dT/dx = 0 (Von Neumann) and T0(nx) =0 (DIRICHLET)
    T_old(1) = T_old(2); T_old(nx) = 0
  end do
  write(*,*) "=== Finished stabilization loop for C0 and T0 >.< ==="
  write(*,*)
  C_init = C_old
  T_init = T_old

  !======================================================================
  call cpu_time(t0)          ! Start timing the simulation
  prog_step = nt / 100       ! Print progress every 1% of total steps

  !======================================================================
  ! q main loop
  !======================================================================
  step_size_q = q_max / nq
  q = 0._dp 
  do i=1, nq
    q(i) = i * step_size_q
  end do
  ! q is an array from 0 to q_max, taking step_size_q = q_max / nq
  
  nan_here = .false.

  do j=1, nq
    !======================================================================
    ! Reset variables for growth rate
    !======================================================================
    flag_growth_rate = .true. 
    Cq_max_old      = 0._dp
    growth_rate_old = 0._dp
    !======================================================================
    ! Load flat front profile
    !======================================================================
    C_old = C_init
    T_old = T_init
    !======================================================================
    ! Initializing arrays
    !======================================================================
    Cq_old = 0._dp
    Tq_old = 0._dp
    Wq_old = 0._dp
    Psiq_old = 0._dp

    !! This is only for seeding the random number generator
    call random_seed(size=nseed)
    allocate(seed(nseed)); 
    seed=12345; 
    call random_seed(put=seed); 
    deallocate(seed)

    !======================================================================
    ! Initial perturbation
    !======================================================================
    do i=noise_ini+1, noise_end
        call random_number(r); Cq_old(i) = 1.0e-3_dp * r
        call random_number(r); Tq_old(i) = 1.0e-3_dp * r
    enddo

    ! Cq = [0,0... random...0,0]
    ! Tq = [0,0... random...0,0]
    ! Wq = [0,0...0,0]
    ! Psiq = [0,0...,0,0]

    !======================================================================
    ! Diagonals (part 1)
    !======================================================================
    ! Initialazing arrays and adding padding for a and c  a(1) = 0 and c(nx-2) = 0
    a_vort=0._dp ;b_vort=1._dp; c_vort=0._dp; d_vort=0._dp
    a_str=0._dp ; b_str=1._dp;  c_str=0._dp ; d_str=0._dp

    ! Compute coefficients that do NOT  change in time

    ! Vorticity (Vort)
    if (normalized_sc) then
        a_vort(2:nx-1) = v0/(Sc*2*dx) + (1.)/dx**2
        b_vort(2:nx-1) = -2./dx**2 - q(j)**2 - 1/(Sc*dt)
        c_vort(2:nx-1) = (1.)/dx**2 - v0/(Sc*2.*dx)
    else
        a_vort(2:nx-1) = -dt*(Sc/dx**2 - v0/(2*dx))
        b_vort(2:nx-1) = 1 + dt*(Sc*q(j)**2 + 2*Sc/dx**2)
        c_vort(2:nx-1) = -dt*(Sc/dx**2 + v0/(2*dx))
    end if


    ! Stream function (Str)
    a_str(2:nx-1)= 1/dx**2
    b_str(2:nx-1) = -2/dx**2 - q(j)**2
    c_str(2:nx-1)= 1/dx**2

  
    !======================================================================
    ! Time loop Cq, Tq, Vorticity and Stream Function
    !======================================================================
      do i=0,nt
        !======================================================================
        ! Solving for flat front solutions C0 and T0 using Euler explicit methods
        ! C0
        C_new(2:nx-1) = C_old(2:nx-1)+ &
                      dt/dx**2*(C_old(3:nx)-2*C_old(2:nx-1)+C_old(1:nx-2))+ &
                      dt*(C_old(2:nx-1)**2)*(1-C_old(2:nx-1))+&
                      v0*dt/(2*dx)*(C_old(3:nx)-C_old(1:nx-2))
        ! T0
        T_new(2:nx-1)=T_old(2:nx-1)+&
                      Le*dt/dx**2*(T_old(3:nx)-2*T_old(2:nx-1)+T_old(1:nx-2))+ &
                      dt*(C_old(2:nx-1)**2)*(1-C_old(2:nx-1))+&
                      v0*dt/(2*dx)*(T_old(3:nx)-T_old(1:nx-2))
        ! Update
        C_old = C_new
        T_old = T_new  
        ! C0 and T0 Boundary conditions 
        ! C0(1)=1 = 1, C0(nx)=0 (DIRICHLET)
        C_old(1) = 1; C_old(nx) = 0
        ! dT/dx = 0 (Von Neumann) and T0(nx) =0 (DIRICHLET)
        T_old(1) = T_old(2); T_old(nx) = 0

        !======================================================================
        ! Diagonals (part 2)
        !======================================================================
        ! Compute coefficients that DO change in time

        ! Vorticity (Vort)
        if (normalized_sc) then
          d_vort(2:nx-1)= -Wq_old(2:nx-1)/(sc*dt) - q(j)*Ra*Tq_old(2:nx-1)
          ! d_vort(2:nx-1)= Wq_old(2:nx-1)/(sc*dt) - q(j)*Ra*Tq_old(2:nx-1)
        else
          d_vort(2:nx-1)= Wq_old(2:nx-1)-dt*q(j)*Ra*Sc*Tq_old(2:nx-1)
        end if

        ! Stream function (Str)
        d_str(2:nx-1)=Wq_old(2:nx-1)
        !======================================================================
        ! Boundary conditions

        ! Voricity 
        a_vort(2)  = 0.0_dp; d_vort(1) = 0.0_dp ! Wq(0)  = 0 
        c_vort(nx-1) = 0.0_dp; d_vort(nx)= 0.0_dp ! Wq(nx) = 0 

        ! Stream function
        a_str(2)  = 0.0_dp; d_str(1) = 0.0_dp ! Psi(0) = 0 
        c_str(nx-1) = 0.0_dp; d_str(nx)= 0.0_dp ! Psi(nx) = 0 
      !======================================================================

        ! The arrays must be of the form (padding added for a and c):
        ! a_vort=[0, 0, a2 ... a_n-1,0] ; b_vort=[1, b1... b_n-1, 1]       ; c_vort=[0,c1...c_n-2, 0, 0]    ; d_vort=[0, d1-a1, d2...d_n-1, 0]
        ! a_str=[0, 0, a2 ... a_n-1,0]  ; b_str=[1, b1... b_n-1, 1]        ; c_str=[0,c1...c_n-2, 0, 0]     ; d_str=[0, d1-a1, d2...d_n-1, 0]

        ! Check if matrix is diagonally dominant: |b(i)| ≥ |a(i)| + |c(i)|
        ! call check_diag_dom("Eq13 wq",a_vort,b_vort,c_vort,nx,i)
        ! call check_diag_dom("Eq14 psi",a_str,b_str,c_str,nx,i)

        ! Solving the Tridiagonal sistem 
        !======================================================================
        ! Explicit update para Cq y Tq
        !======================================================================
        ! Concentración perturbación (Ecuación 11)
        Cq_new(2:nx-1) = Cq_old(2:nx-1) & 
                + dt * ( (Cq_old(3:nx) - 2*Cq_old(2:nx-1) + Cq_old(1:nx-2)) / dx**2 ) & 
                + v0*dt/(2*dx) * ( Cq_old(3:nx) - Cq_old(1:nx-2) ) & 
                - dt*q(j)**2 * Cq_old(2:nx-1) & 
                + dt * C_old(2:nx-1)*(2._dp - 3._dp*C_old(2:nx-1)) * Cq_old(2:nx-1) & 
                - dt * q(j)/(2*dx) * Psiq_old(2:nx-1) * ( C_old(3:nx) - C_old(1:nx-2) )

        ! Temperatura perturbación (Ecuación 12)
        Tq_new(2:nx-1) = Tq_old(2:nx-1) & 
                + Le*dt * ( (Tq_old(3:nx) - 2*Tq_old(2:nx-1) + Tq_old(1:nx-2)) / dx**2 ) & 
                + v0*dt/(2*dx) * ( Tq_old(3:nx) - Tq_old(1:nx-2) ) & 
                - Le*q(j)**2 * dt * Tq_old(2:nx-1) & 
                - dt * q(j)/(2*dx) * Psiq_old(2:nx-1) * ( T_old(3:nx) - T_old(1:nx-2) ) & 
                + dt * C_old(2:nx-1)*(2._dp - 3._dp*C_old(2:nx-1)) * Cq_old(2:nx-1)

        Cq_new(1) = 0._dp
        Cq_new(nx) = 0._dp

        Tq_new(1) = Tq_new(2)
        Tq_new(nx) = 0._dp
        !======================================================================
        ! Solving Tridiagonal sistem
        !======================================================================
        call tri_dig(a_vort(1:nx), b_vort(1:nx), c_vort(1:nx), d_vort(1:nx), Wq_new(1:nx)  ,nx)
        call tri_dig(a_str(1:nx),  b_str(1:nx),  c_str(1:nx),  d_str(1:nx),  Psiq_new(1:nx),nx)
        
        ! Check for NaN values
        nan_here = .false.     ! ← se reinicia en cada paso temporal

        if (any(.not.(Cq_new == Cq_new))) then
          write(*,'(">> NaN in Cq_new  at i=",I0,"  (q=",F7.4,")")') i, q(j)
          nan_here = .true.
        end if

        if (any(.not.(Tq_new == Tq_new))) then
          write(*,'(">> NaN in Tq_new  at i=",I0,"  (q=",F7.4,")")') i, q(j)
          nan_here = .true.
        end if

        if (any(.not.(Wq_new == Wq_new))) then
          write(*,'(">> NaN in Wq_new  at i=",I0,"  (q=",F7.4,")")') i, q(j)
          nan_here = .true.
        end if

        if (any(.not.(Psiq_new == Psiq_new))) then
          write(*,'(">> NaN in Psiq_new at i=",I0,"  (q=",F7.4,")")') i, q(j)
          nan_here = .true.
        end if

        if (nan_here) then
          C0_save(j,:)   = C_old(:)
          T0_save(j,:)   = T_old(:)
          Cq_save(j,:)   = Cq_old(:)
          Tq_save(j,:)   = Tq_old(:)
          Wq_save(j,:)   = Wq_old(:)
          Psiq_save(j,:) = Psiq_old(:)
          growth_rate(j) = growth_rate_old

          write(*,'(">> Jumping to next q (j=",I0,")")') j
          exit        
        end if
        !======================================================================
        ! Growth rate of the perturbation
        !======================================================================
        ! We calculate the growth rate of the perturbation (sigma) from the derivative of the perturbation Cq
        ! d/dt Cq = sigma Cq
        ! Discrtizing: sigma_max = (Cq_max_new - Cq_max_old)/ (dt *  Cq_max_old )
        ! We need to find the max value in abs(Cq), save it, and the compare it to the next new max value
        ! Since we compare every growth_steps  steps
        ! growth_rate_new = (Cq_max_new - Cq_max_old ) / (dt* growth_steps * Cq_max_old)

        ! flag_log_form = true
        ! Cq (t) = Cq(t-1) exp(growth_rate * delta t) , where delta t = dt * growth_steps
        ! ln (Cq (t) / Cq(t-1) ) = growth_rate * delta t
        ! >> growth_rate  = (ln (Cq (t) / Cq(t-1) )) / delta t
        ! note that: growth_rate_relative + 1 = (Cq_max_new-Cq_max_old)/Cq_max_old + 1  = (Cq_max_new-Cq_max_old + Cq_max_old )/Cq_max_old 
        !                                     =  (Cq_max_new)/Cq_max_old
        if ( i > 100000 .and. mod(i, growth_steps) == 0 .and. flag_growth_rate) then
          Cq_max_new = maxval(abs(Cq_new))

          if (Cq_max_old == 0._dp) then        
              Cq_max_old = Cq_max_new
          else          
              if (flag_log_form) then
                growth_rate_relative = (Cq_max_new-Cq_max_old)/Cq_max_old
                growth_rate_new =   log(abs(growth_rate_relative + 1))/(dt * growth_steps)    
              else          
                growth_rate_new = (Cq_max_new - Cq_max_old) /(dt * growth_steps * Cq_max_old)
              endif

              ! Growth rate convergence
              if (abs(growth_rate_old - growth_rate_new) < 1.0e-4) then
                flag_growth_rate = .false.

                C0_save(j,:)   = C_old(:)
                T0_save(j,:)   = T_old(:)
                Cq_save(j,:)   = Cq_old(:)
                Tq_save(j,:)   = Tq_old(:)
                Wq_save(j,:)   = Wq_old(:)
                Psiq_save(j,:) = Psiq_old(:)
                growth_rate(j) = growth_rate_new
                write(*,'("Growth-rate stabilised: I= ",I9,"  (q=",F7.4,",  sigma=",E12.5,")")')  i, q(j), growth_rate_new
                exit
              end if

              growth_rate_old = growth_rate_new
              Cq_max_old      = Cq_max_new
          end if
        end if


        !======================================================================
        ! Update variables
        Cq_old=Cq_new; Tq_old=Tq_new
        Wq_old=Wq_new; Psiq_old=Psiq_new   

        !======================================================================
        ! Progress
        !======================================================================
        if(mod(i,prog_step)==0)then
            call cpu_time(tcur)
            pct=100._dp*real(i,dp)/real(nt,dp)
            write(*,'("q=",F7.5,"  j=",I3,"  i=",I7,"  Progres: ",F6.2," %   Total Time: ",F8.1," s")') q(j), j, i, pct, tcur - t0
        end if
        !======================================================================
        ! Saving Values at nt
        !======================================================================
        if (i == nt) then
          C0_save(j, :)   = C_old(:)
          T0_save(j, :)   = T_old(:)
          Cq_save(j, :)   = Cq_old(:)
          Tq_save(j, :)   = Tq_old(:)
          Wq_save(j, :)   = Wq_old(:)
          Psiq_save(j, :) = Psiq_old(:)
          growth_rate(j) = growth_rate_old
          if (.not. flag_growth_rate) then
            write(*,'("Growth rate converged for q = ",F8.5,"   sigma = ",E12.5)') q(j), growth_rate(j)
          end if
          write(*,*) "Saved values for q =", q(j)
          write(*,*)
        end if
      end do ! end time loop
  end do ! end q loop
  !======================================================================
  ! Writting Files
  !======================================================================
  do k = 1, nx
      write(10,*) (C0_save(jj,k), jj=1,nq)
      write(11,*) (T0_save(jj,k), jj=1,nq)
      write(12,*) (Cq_save(jj,k), jj=1,nq)
      write(13,*) (Tq_save(jj,k), jj=1,nq)
      write(14,*) (Wq_save(jj,k), jj=1,nq)
      write(15,*) (Psiq_save(jj,k), jj=1,nq)
  end do

  do jj=1,nq
    write(16,'(F12.5)') growth_rate(jj)
  end do

  close(10)
  close(11)
  close(12)
  close(13)
  close(14)
  close(15)
  close(16)
end program main_explicit11_12